# Numpy Tutorial

In [125]:
import numpy as np

In [117]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [118]:
d = np.array([1,2,3,4,5])
d

array([1, 2, 3, 4, 5])

In [119]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [120]:
c = np.array([1,2,3])
c

array([1, 2, 3])

## reshape : Making matris

In [121]:
a = a.reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [122]:
a.shape

(5, 4)

In [123]:
b = b.reshape(5,1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

## ndim : Nombre of dimansions

In [124]:
b.ndim

2

## Operations

In [128]:
s = np.arange(5)
w = np.array([5,6,7,8,9])
s

array([0, 1, 2, 3, 4])

In [133]:
y = s + w
y

array([ 5,  7,  9, 11, 13])

In [135]:
yy = s-w
yy

array([-5, -5, -5, -5, -5])

In [137]:
w - s

array([5, 5, 5, 5, 5])

In [138]:
s * w

array([ 0,  6, 14, 24, 36])

In [139]:
s / w

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [141]:
s

array([0, 1, 2, 3, 4])

In [153]:
ss = s<1
ss

array([ True, False, False, False, False])

In [161]:
for i in ss:
    if i == False:
        print("OK")
    

OK
OK
OK
OK
